// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("aglet")>]
[<assembly: AssemblyProductAttribute("aglet")>]
[<assembly: AssemblyDescriptionAttribute("aglet: a github label editing tool for dotnet")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "aglet"
    let [<Literal>] AssemblyProduct = "aglet"
    let [<Literal>] AssemblyDescription = "aglet: a github label editing tool for dotnet"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
